# Generated by Django 4.2.1 on 2023-06-07 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='property_images/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
