# Generated by Django 4.2.1 on 2023-06-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_property_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='address',
            new_name='location',
        ),
        migrations.AddField(
            model_name='property',
            name='max_price',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='min_price',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
