# Generated by Django 4.2.1 on 2023-06-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_property_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='address',
            new_name='location',
        ),
    ]
