# Generated by Django 4.2.1 on 2023-06-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_address_property_location_property_max_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='max_price',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='min_price',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
