# Generated by Django 4.2.1 on 2023-06-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_property_max_price_alter_property_min_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='max_price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='min_price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
