# Generated by Django 4.2.1 on 2023-06-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_property_max_price_alter_property_min_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
