# Generated by Django 4.2.1 on 2023-06-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_property_max_price_alter_property_min_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='min_price',
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
