# Generated by Django 4.2.1 on 2023-06-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_property_max_price_remove_property_min_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(max_length=20),
        ),
    ]
